---
name: ShellCheck

"on":
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  call-common-shellcheck:
    uses: Seika139/.github/.github/workflows/shellcheck.yml@main
    secrets: inherit
